config/routes.rb
Hams::Application.routes.draw do

  root to:'hotels#index', top: "5"

  resources :streets

  resources :cities

  resources :states

  resources :countries

  devise_for :users

  resources :assets
  
  resources :hotels do
    resources :comments, only: [:create]
  end

  namespace :dynamic_select do
    get ':country_id/states', to: 'states#index', as: 'states'
    get ':state_id/cities',   to: 'cities#index', as: 'cities'
    get ':city_id/streets', to: 'streets#index', as: 'streets'
  end

  

end

app/models/state.rb
class State < ActiveRecord::Base
  validates_presence_of :title
  validates_presence_of :country
  belongs_to :country
  has_many :cities
end

app/controllers/dynamic_select/states_controller.rb
module DynamicSelect
  class StatesController < ApplicationController
    respond_to :json

    def index
      @states = State.where(country_id: params[:country_id])
      respond_with(@states) 
    end
  end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:index, :show]
  respond_to :html
  def index
    @states = State.all
    respond_with @states
  end

  def show
  end

  def new
    @state = State.new
    respond_with @state
  end

  def edit
  end

  def create
    @state = State.create(state_params)
    respond_with @state
  end

  def update
    @state.update(state_params)
    respond_with @state
  end

  def destroy
    @state.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
      @state = State.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def state_params
      params.require(:state).permit(:title, :country_id)
    end
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/states/_form.html.haml
= simple_form_for(@state) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.association :country

  .form-actions
    = f.button :submit

app/views/states/edit.html.haml
%h1 Editing state

= render 'form'

= link_to 'Show', @state
\|
= link_to 'Back', states_path

app/views/states/index.html.haml
%h1 Listing states

%table
  %tr
    %th Title
    %th Country
    %th
    %th
    %th

  - @states.each do |state|
    %tr
      %td= state.title
      %td= state.country.title
      %td= link_to 'Show', state
      %td= link_to 'Edit', edit_state_path(state)
      %td= link_to 'Destroy', state, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New State', new_state_path

app/views/states/new.html.haml
%h1 New state

= render 'form'

= link_to 'Back', states_path

app/views/states/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @state.title
%p
  %b Country:
  = @state.country.title

= link_to 'Edit', edit_state_path(@state)
\|
= link_to 'Back', states_path