config/routes.rb
Hams::Application.routes.draw do

  root to:'hotels#index', top: "5"

  resources :streets

  resources :cities

  resources :states

  resources :countries

  devise_for :users

  resources :assets
  
  resources :hotels do
    resources :comments, only: [:create]
  end

  namespace :dynamic_select do
    get ':country_id/states', to: 'states#index', as: 'states'
    get ':state_id/cities',   to: 'cities#index', as: 'cities'
    get ':city_id/streets', to: 'streets#index', as: 'streets'
  end

  

end

app/models/street.rb
class Street < ActiveRecord::Base
  belongs_to :city
  validates_presence_of :title
  validates_presence_of :city
end

app/controllers/dynamic_select/streets_controller.rb
module DynamicSelect  
  class StreetsController < ApplicationController
    respond_to :json
    def index
      @streets = Street.where(city_id: params[:city_id])
      respond_with (@streets)
    end

  end
end

app/controllers/streets_controller.rb
class StreetsController < ApplicationController
  before_action :set_street, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:index, :show]
  respond_to :html

  def index
    @streets = Street.all
    respond_with @streets
  end

  def show
  end

  def new
    @street = Street.new
  end

  def edit
  end

  def create
    @street = Street.create(street_params)
    respond_with @street
  end

  def update
    @street.update(street_params)
    respond_with @street
  end

  def destroy
    @street.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_street
      @street = Street.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def street_params
      params.require(:street).permit(:title, :city_id)
    end
end

app/helpers/streets_helper.rb
module StreetsHelper
end

app/views/streets/_form.html.haml
= simple_form_for(@street) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.association :city

  .form-actions
    = f.button :submit

app/views/streets/edit.html.haml
%h1 Editing street

= render 'form'

= link_to 'Show', @street
\|
= link_to 'Back', streets_path

app/views/streets/index.html.haml
%h1 Listing streets

%table
  %tr
    %th Title
    %th City
    %th
    %th
    %th

  - @streets.each do |street|
    %tr
      %td= street.title
      %td= street.city.title
      %td= link_to 'Show', street
      %td= link_to 'Edit', edit_street_path(street)
      %td= link_to 'Destroy', street, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Street', new_street_path

app/views/streets/new.html.haml
%h1 New street

= render 'form'

= link_to 'Back', streets_path

app/views/streets/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @street.title
%p
  %b City:
  = @street.city.title

= link_to 'Edit', edit_street_path(@street)
\|
= link_to 'Back', streets_path