config/routes.rb
Hams::Application.routes.draw do

  root to:'hotels#index', top: "5"

  resources :streets

  resources :cities

  resources :states

  resources :countries

  devise_for :users

  resources :assets
  
  resources :hotels do
    resources :comments, only: [:create]
  end

  namespace :dynamic_select do
    get ':country_id/states', to: 'states#index', as: 'states'
    get ':state_id/cities',   to: 'cities#index', as: 'cities'
    get ':city_id/streets', to: 'streets#index', as: 'streets'
  end

  

end

app/models/city.rb
class City < ActiveRecord::Base
  validates_presence_of :title
  validates_presence_of :state
  belongs_to :state
  has_many   :streets
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:index, :show]
  respond_to :html

  def index
    @cities = City.all
    respond_with @cities
  end

  def show
  end

  def new
    @city = City.new
  end

  def edit
  end

  def create
    @city = City.create(city_params)
    respond_with @city
  end

  def update
    @city.update(city_params)
    respond_with @city
  end

  def destroy
    @city.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:title, :state_id)
    end
end

app/controllers/dynamic_select/cities_controller.rb
module DynamicSelect  
  class CitiesController < ApplicationController
    respond_to :json
    def index
      @cities = City.where(state_id: params[:state_id])
      respond_with(@cities) 
    end
  end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/_form.html.haml
= simple_form_for(@city) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.association :state

  .form-actions
    = f.button :submit

app/views/cities/edit.html.haml
%h1 Editing city

= render 'form'

= link_to 'Show', @city
\|
= link_to 'Back', cities_path

app/views/cities/index.html.haml
%h1 Listing cities

%table
  %tr
    %th Title
    %th State
    %th
    %th
    %th

  - @cities.each do |city|
    %tr
      %td= city.title
      %td= city.state.title
      %td= link_to 'Show', city
      %td= link_to 'Edit', edit_city_path(city)
      %td= link_to 'Destroy', city, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New City', new_city_path

app/views/cities/new.html.haml
%h1 New city

= render 'form'

= link_to 'Back', cities_path

app/views/cities/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @city.title
%p
  %b State:
  = @city.state.title

= link_to 'Edit', edit_city_path(@city)
\|
= link_to 'Back', cities_path