config/routes.rb
Hams::Application.routes.draw do

  root to:'hotels#index', top: "5"

  resources :streets

  resources :cities

  resources :states

  resources :countries

  devise_for :users

  resources :assets
  
  resources :hotels do
    resources :comments, only: [:create]
  end

  namespace :dynamic_select do
    get ':country_id/states', to: 'states#index', as: 'states'
    get ':state_id/cities',   to: 'cities#index', as: 'cities'
    get ':city_id/streets', to: 'streets#index', as: 'streets'
  end

  

end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
	has_many :comments
  has_many :assets
  belongs_to :country
  belongs_to :state
  belongs_to :city
  belongs_to :street

	validates_presence_of :title
  
  scope :top_rating, -> {order('avg_rating DESC')}
  scope :limit_top_rating,  ->(limit_count) {top_rating.limit(limit_count)}
  def update_rating
    comments_count = comments.count
      if comments_count == 0
        avg_rating = 0 
      else
        avg_rating = comments.sum(:rating).to_f / comments_count
      end
    self.update_attributes!(avg_rating: avg_rating)
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :set_hotel, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:index, :show]
  respond_to :html

  def index
    if params[:top]
      @hotels = Hotel.limit_top_rating(params[:top])
    else
      @hotels = Hotel.all
    end
    respond_with @hotels
  end

  def show
    @hotel = Hotel.find(params[:id])
    respond_with(@hotel, @comment, @comments)
  end

  def new
    @hotel = Hotel.new
  end

  def edit
  end

  def create
    @hotel = Hotel.create(hotel_params)
    respond_with @hotel
  end

  def update
    @hotel.update(hotel_params)
    respond_with @hotel
  end

  def destroy
    @hotel.destroy
  end

  private
    def set_hotel
      @hotel = Hotel.find(params[:id])
    end

    def hotel_params
      params.require(:hotel).permit(:title, :room_description, :price_for_room, :breakfast_included, :country_id, :state_id, :city_id, :street_id)
    end
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/hotels/_fileupload.html.erb
<% @assets = @hotel.assets.build%>
<%= form_for @assets , :url => { :controller => "assets", :action => "index", :hotel_id => @hotel.id},:html => { :multipart => true, :id => "fileupload"  } do |f| %>
<div class="row fileupload-buttonbar">
  <div class="span7">
    <span class="btn btn-success fileinput-button">
      <i class="icon-plus icon-white"></i>
      <span>Add files...</span>
      <%= f.file_field :photo, multiple: true, name: 'asset[photo]'%>
      <%= f.hidden_field :hotel_id, value: @hotel.id %>
    </span>
    <button type="submit" class="btn btn-primary start">
      <i class="icon-upload icon-white"></i>
      <span>Start upload</span>
    </button>
    <button type="reset" class="btn btn-warning cancel">
      <i class="icon-ban-circle icon-white"></i>
      <span>Cancel upload</span>
    </button>
    <button type="button" class="btn btn-danger delete">
      <i class="icon-trash icon-white"></i>
      <span>Delete</span>
    </button>
    <input type="checkbox" class="toggle">
  </div>
  <div class='span5'>
    <div class="progress progress-success progress-striped active fade">
      <div class="bar" style="width:0%;"></div>
    </div>
  </div>
</div>
<!-- The loading indicator is shown during image processing -->
<div class="fileupload-loading"></div>
<br>
 <!-- The table listing the files available for upload/download -->
<table class="table table-striped"><tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery"></tbody>
</table>
<% end %>

<script>
  var fileUploadErrors = {
  maxFileSize: 'File is too big',
  minFileSize: 'File is too small',
  acceptFileTypes: 'Filetype not allowed',
  maxNumberOfFiles: 'Max number of files exceeded',
  uploadedBytes: 'Uploaded bytes exceed file size',
  emptyResult: 'Empty file upload result'
  };
</script>
<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">
  {% for (var i=0, file; file=o.files[i]; i++) { %}
  <tr class="template-upload fade">
    <td class="preview"><span class="fade"></span></td>
    <td class="name"><span>{%=file.name%}</span></td>
    <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
    {% if (file.error) { %}
    <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
    {% } else if (o.files.valid && !i) { %}
    <td>
      <div class="progress progress-success progress-striped active"><div class="bar" style="width:0%;"></div></div>
    </td>
    <td class="start">{% if (!o.options.autoUpload) { %}
      <button class="btn btn-primary">
        <i class="icon-upload icon-white"></i>
        <span>{%=locale.fileupload.start%}</span>
      </button>
      {% } %}</td>
    {% } else { %}
    <td colspan="2"></td>
    {% } %}
    <td class="cancel">{% if (!i) { %}
      <button class="btn btn-warning">
        <i class="icon-ban-circle icon-white"></i>
        <span>{%=locale.fileupload.cancel%}</span>
      </button>
      {% } %}</td>
  </tr>
  {% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
  {% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
      {% if (file.error) { %}
        <td></td>
        <td class="name"><span>{%=file.name%}</span></td>
        <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
        <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
        {% } else { %}
        <td class="preview">{% if (file.thumbnail_url) { %}
          <a href="{%=file.url%}" title="{%=file.name%}" rel="gallery" download="{%=file.name%}"><img src="{%=file.thumbnail_url%}"></a>
          {% } %}</td>
        <td class="name">
          <img src="{%=file.url%}"></a>
          <a href="{%=file.url%}" title="{%=file.name%}" rel="{%=file.thumbnail_url&&'gallery'%}" download="{%=file.name%}">{%=file.name%}</a>
        </td>
        <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
        <td colspan="2"></td>
        {% } %}
      <td class="delete">
        <button class="btn btn-danger" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}">
          <i class="icon-trash icon-white"></i>
          <span>{%=locale.fileupload.destroy%}</span>
        </button>
        <input type="checkbox" name="delete" value="1">
      </td>
    </tr>
    {% } %}
</script>

<script type="text/javascript" charset="utf-8">
  $(function () {
      // Initialize the jQuery File Upload widget:
      $('#fileupload').fileupload(
        {paramName: 'asset[photo]'});
      //
      // Load existing files:
      // "http://localhost:3000/assets?locale=ru"
      $.getJSON($('#fileupload').prop('action') , function (files) {
        var fu = $('#fileupload').data('blueimpFileupload'),
          template;
        fu._adjustMaxNumberOfFiles(-files.length);
        console.log(files);
        template = fu._renderDownload(files)
          .appendTo($('#fileupload .files'));
        // Force reflow:
        fu._reflow = fu._transition && template.length &&
          template[0].offsetWidth;
        template.addClass('in');
        $('#loading').remove();
      });

  });
</script>

app/views/hotels/_form.html.haml
= simple_form_for @hotel do |f|
  - if @hotel.errors.any?
    #error_explanation
      %h2= "#{pluralize(@hotel.errors.count, "error")} prohibited this hotel from being saved:"
      %ul
        - @hotel.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.input :title
  .field
    = f.input :room_description
  .field
    = f.label :country
    = f.collection_select :country_id, Country.all, :id, :title,
      {include_blank: true},
        { data: {dynamic_selectable_url: dynamic_select_states_path(':country_id'),
          dynamic_selectable_target: '#hotel_state_id'}}
        
  .field
    = f.label :state
    = f.collection_select :state_id, @hotel.country.try(:states) || [],  :id, :title, {include_blank: true}, {data: {dynamic_selectable_url: dynamic_select_cities_path(':state_id'), dynamic_selectable_target: '#hotel_city_id'}}
     
  .field
    = f.label :city
    = f.collection_select :city_id, @hotel.state.try(:cities) || [], :id, :title, {include_blank: true}, {data: {dynamic_selectable_url: dynamic_select_streets_path(':city_id'), dynamic_selectable_target: '#hotel_street_id'}}

  .field
    = f.label :street
    = f.collection_select :street_id, @hotel.city.try(:streets) || [], :id, :title, {include_blank: true}
  .field
    = f.input :price_for_room
  .field
    = f.input :breakfast_included
  .actions
    = f.button :submit

app/views/hotels/edit.html.haml
%h1 Editing hotel

= render 'form'
= render 'fileupload'

= link_to 'Show', @hotel
\|
= link_to 'Back', hotels_path

app/views/hotels/index.html.haml
%ul.thumbnails
  - @hotels.each do |hotel|
    %li.span12
      %hr
      %h2.hotel_title= link_to "#{hotel.title}", hotel 
      = truncate(hotel.room_description, length: 300) 
      = link_to 'more', hotel
      %div= "rating #{hotel.avg_rating}"

%br
-if user_signed_in?
  = link_to 'New Hotel', new_hotel_path, class:'btn'

app/views/hotels/new.html.haml
%h1 New hotel

= render 'form'

= link_to 'Back', hotels_path

app/views/hotels/show.html.haml
%p#notice= notice

%p
	%h1
	%b= @hotel.title
%p
	= @hotel.room_description
%p
	%b price -  
	= @hotel.price_for_room
	%b breakfast -  
	= @hotel.breakfast_included

- @hotel.assets.each do |asset|
	= image_tag(asset.photo.url(:medium)) 
- if user_signed_in?
	= render 'comments/form'
%ul
	= render @hotel.comments

- if user_signed_in?
	= link_to 'Edit', edit_hotel_path(@hotel)
	\|
	= link_to 'Back', hotels_path